name: Test

on: [push]

jobs:
  build:
    strategy:
      matrix:
        version: [7.3, 7.4, 7.5]
    runs-on: ubuntu-latest
    name: OpenBSD x86_64
    steps:
    - uses: actions/checkout@v4
    - name: ${{ matrix.version }}
      id: test
      uses: vmactions/openbsd-vm@v1.0.8
      with:
        sync: sshfs
        release: ${{ matrix.version }}
        run: uname -a > uwu-${{ matrix.version }}.txt
    - uses: actions/upload-artifact@v4
      with:
        name: uname-${{ matrix.version }}
        path: uwu-${{ matrix.version }}.txt
  merge:
    needs: build
    runs-on: ubuntu-latest
    name: Merge All artifacts
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: artifacts
      - name: Display structure of downloaded files
        run: ls -la artifacts/
