name: Test

on: [push]

jobs:
  openbsd:
    strategy:
      matrix:
        version: [7.3, 7.4, 7.5]
    runs-on: ubuntu-latest
    name: OpenBSD x86_64
    steps:
    - uses: actions/checkout@v4
    - name: ${{ matrix.version }}
      id: test
      uses: vmactions/openbsd-vm@v1
      with:
        sync: sshfs
        release: ${{ matrix.version }}
        run: uname -a > uname-OpenBSD-x86_64-${{ matrix.version }}.txt
    - uses: actions/upload-artifact@v4
      with:
        name: uname-OpenBSD-x86_64-${{ matrix.version }}
        path: uname-OpenBSD-x86_64-${{ matrix.version }}.txt
  freebsd:
    strategy:
      matrix:
        version: [12.4, 13.2, 13.3, 14.0]
    runs-on: ubuntu-latest
    name: FreeBSD x86_64
    steps:
    - uses: actions/checkout@v4
    - name: ${{ matrix.version }}
      id: test
      uses: vmactions/freebsd-vm@v1
      with:
        sync: sshfs
        release: ${{ matrix.version }}
        run: uname -a > uname-FreeBSD-x86_64-${{ matrix.version }}.txt
    - uses: actions/upload-artifact@v4
      with:
        name: uname-FreeBSD-x86_64-${{ matrix.version }}
        path: uname-FreeBSD-x86_64-${{ matrix.version }}.txt
  netbsd:
    strategy:
      matrix:
        version: [9.0, 9.1, 9.2, 9.3, 10.0]
    runs-on: ubuntu-latest
    name: NetBSD x86_64
    steps:
    - uses: actions/checkout@v4
    - name: ${{ matrix.version }}
      id: test
      uses: vmactions/netbsd-vm@v1
      with:
        sync: sshfs
        release: ${{ matrix.version }}
        run: uname -a > uname-NetBSD-x86_64-${{ matrix.version }}.txt
    - uses: actions/upload-artifact@v4
      with:
        name: uname-NetBSD-x86_64-${{ matrix.version }}
        path: uname-NetBSD-x86_64-${{ matrix.version }}.txt
  merge:
    needs: [openbsd, freebsd, netbsd]
    runs-on: ubuntu-latest
    name: Merge All artifacts
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: .
      - name: Merge
        run: |
          mkdir unames
          mv uname-*/* unames/
      - uses: geekyeggo/delete-artifact@v5
        with:
          name: uname-*
      - uses: actions/upload-artifact@v4
        with:
          name: unames
          path: unames/*
